# Generated by Django 4.1.4 on 2023-01-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_list", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=30)),
                (
                    "score_to_pass",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="required score in %",
                        max_digits=100,
                    ),
                ),
            ],
        ),
    ]
