# Generated by Django 4.1.4 on 2022-12-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("question", models.CharField(max_length=1000)),
                ("answer1", models.IntegerField()),
                ("answer2", models.IntegerField()),
            ],
        ),
    ]
